# Test for at hente alle film
GET http://localhost:7070/api/movies/all
Accept: application/json

###

# Test for at hente film baseret på rating
GET http://localhost:7070/api/movies/rating/8
Accept: application/json

###

# Test for at hente film baseret på genre
GET http://localhost:7070/api/movies/genre/Action
Accept: application/json

###

# Test for at hente film baseret på udgivelsesår
GET http://localhost:7070/api/movies/year/2022
Accept: application/json

###

# Test for at hente en film baseret på IMDb ID
GET http://localhost:7070/api/movies/imdb/833339
Accept: application/json

###

# Test for at hente film baseret på instruktør
GET http://localhost:7070/api/movies/instructor/Thomas Vinterberg
Accept: application/json

###

# Test for at hente film baseret på skuespiller
GET http://localhost:7070/api/movies/actor/Lars Ranthe
Accept: application/json

###

# Test for at hente film baseret på titel
GET http://localhost:7070/api/movies/title/Druk
Accept: application/json

###

# Test for at hente film med et minimum antal stemmer
GET http://localhost:7070/api/movies/minvotes/100
Accept: application/json
