# .github/workflows/workflow.yml
name: CI/CD WORKFLOW
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Behold versionen, da den er opdateret

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Behold versionen, da den er opdateret
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Login to Docker Hub
        uses: docker/login-action@v3  # Behold versionen, da den er opdateret
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Opdateret til v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Opdateret til v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sem3_sp1:latest
